Repository sneakycrow/izfs, pull requests merged in 2022-12, with the labels that each got.

#7 Replaces webpack scaffolding with vite scaffolding
  package-lock.json
  package.json
  tsconfig.json
  web/.gitignore
  web/components/button.tsx
  web/index.html
  web/package-lock.json
  web/package.json
  web/pages/index.html
  web/public/vite.svg
  web/src/App.css
  web/src/App.tsx
  web/src/assets/react.svg
  web/src/index.css
  web/src/main.tsx
  web/src/vite-env.d.ts
  web/tsconfig.json
  web/tsconfig.node.json
  web/vite.config.ts
  webpack.config.js
Labels: enhancement

#15 Re-configure vite to run from the root directory
  package-lock.json
  package.json
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
  web/src/App.tsx
Labels: enhancement

#9 Create FUNDING.yml
  .github/FUNDING.yml
Labels: documentation

#17 add .nvmrc with v18.12.1
  .nvmrc
  README.md
Labels: documentation, enhancement

#22 Polish and consolidate CSS/JS
  package-lock.json
  package.json
  web/index.html
  web/public/.gitkeep
  web/public/vite.svg
  web/src/App.css
  web/src/App.tsx
  web/src/AuthPage.tsx
  web/src/ImageUploader.tsx
  web/src/assets/react.svg
  web/src/index.css
  web/src/services/login-utils.tsx
Labels: enhancement

#21 Add a stylized homepage
  package.json
  web/index.html
  web/public/.gitkeep
  web/public/vite.svg
  web/src/App.css
  web/src/App.tsx
  web/src/assets/react.svg
  web/src/index.css
Labels: enhancement

#24 add description to readme
  README.md
Labels: documentation

#25 Render web output with api package
  api/Cargo.toml
  api/src/main.rs
Labels: enhancement

#27 Initialize Github Actions workflows
  .github/workflows/build-api.yml
  .github/workflows/prerelease.yml
  Dockerfile
Labels: enhancement

#31 Add build status to readme
  README.md
Labels: documentation

#32 Add makefile with install, build, and clean scripts
  Makefile
  README.md
Labels: documentation, enhancement
